<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Visa\HotBiz.cs" />
    <Compile Remove="Visa\VisaCountryService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lvy.Trip.Common\Lvy.Trip.Common.csproj" />
    <ProjectReference Include="..\Lvy.Trip.Persistence\Lvy.Trip.Persistence.csproj" />
  </ItemGroup>

</Project>
