//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvy.Trip.AdminSite.SendWeixinMessage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sh-cct.cn/", ConfigurationName="SendWeixinMessage.SendWeixinMsessageSoap")]
    public interface SendWeixinMsessageSoap {
        
        // CODEGEN: 命名空间 http://www.sh-cct.cn/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendMessage", ReplyAction="*")]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse SendMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse> SendMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://www.sh-cct.cn/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendImage", ReplyAction="*")]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse SendImage(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendImage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse> SendImageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest request);
        
        // CODEGEN: 命名空间 http://www.sh-cct.cn/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendTemplateMessage", ReplyAction="*")]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse SendTemplateMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendTemplateMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse> SendTemplateMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest request);
        
        // CODEGEN: 命名空间 http://www.sh-cct.cn/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendChatMessage", ReplyAction="*")]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse SendChatMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/SendChatMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse> SendChatMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest request);
        
        // CODEGEN: 命名空间 http://www.sh-cct.cn/ 的元素名称 sceneId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/CreateQrCode", ReplyAction="*")]
        Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse CreateQrCode(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sh-cct.cn/CreateQrCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse> CreateQrCodeAsync(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string timeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string signed;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string openId, string content, string timeStamp, string signed) {
            this.openId = openId;
            this.content = content;
            this.timeStamp = timeStamp;
            this.signed = signed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendImage", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequestBody Body;
        
        public SendImageRequest() {
        }
        
        public SendImageRequest(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string timeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string signed;
        
        public SendImageRequestBody() {
        }
        
        public SendImageRequestBody(string openId, string filePath, string timeStamp, string signed) {
            this.openId = openId;
            this.filePath = filePath;
            this.timeStamp = timeStamp;
            this.signed = signed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendImageResponse", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponseBody Body;
        
        public SendImageResponse() {
        }
        
        public SendImageResponse(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendImageResult;
        
        public SendImageResponseBody() {
        }
        
        public SendImageResponseBody(string SendImageResult) {
            this.SendImageResult = SendImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplateMessage", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequestBody Body;
        
        public SendTemplateMessageRequest() {
        }
        
        public SendTemplateMessageRequest(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendTemplateMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string template;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string first;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string param5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string timeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string signed;
        
        public SendTemplateMessageRequestBody() {
        }
        
        public SendTemplateMessageRequestBody(string openId, string template, string first, string param1, string param2, string param3, string param4, string param5, string remark, string timeStamp, string signed) {
            this.openId = openId;
            this.template = template;
            this.first = first;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.remark = remark;
            this.timeStamp = timeStamp;
            this.signed = signed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTemplateMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTemplateMessageResponse", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponseBody Body;
        
        public SendTemplateMessageResponse() {
        }
        
        public SendTemplateMessageResponse(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendTemplateMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTemplateMessageResult;
        
        public SendTemplateMessageResponseBody() {
        }
        
        public SendTemplateMessageResponseBody(string SendTemplateMessageResult) {
            this.SendTemplateMessageResult = SendTemplateMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendChatMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendChatMessage", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequestBody Body;
        
        public SendChatMessageRequest() {
        }
        
        public SendChatMessageRequest(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendChatMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string template;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string timeStamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string signed;
        
        public SendChatMessageRequestBody() {
        }
        
        public SendChatMessageRequestBody(string openId, string template, string nick, string content, string timeStamp, string signed) {
            this.openId = openId;
            this.template = template;
            this.nick = nick;
            this.content = content;
            this.timeStamp = timeStamp;
            this.signed = signed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendChatMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendChatMessageResponse", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponseBody Body;
        
        public SendChatMessageResponse() {
        }
        
        public SendChatMessageResponse(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class SendChatMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendChatMessageResult;
        
        public SendChatMessageResponseBody() {
        }
        
        public SendChatMessageResponseBody(string SendChatMessageResult) {
            this.SendChatMessageResult = SendChatMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQrCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQrCode", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequestBody Body;
        
        public CreateQrCodeRequest() {
        }
        
        public CreateQrCodeRequest(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class CreateQrCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sceneId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string expireSeconds;
        
        public CreateQrCodeRequestBody() {
        }
        
        public CreateQrCodeRequestBody(string sceneId, string expireSeconds) {
            this.sceneId = sceneId;
            this.expireSeconds = expireSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQrCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQrCodeResponse", Namespace="http://www.sh-cct.cn/", Order=0)]
        public Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponseBody Body;
        
        public CreateQrCodeResponse() {
        }
        
        public CreateQrCodeResponse(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sh-cct.cn/")]
    public partial class CreateQrCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateQrCodeResult;
        
        public CreateQrCodeResponseBody() {
        }
        
        public CreateQrCodeResponseBody(string CreateQrCodeResult) {
            this.CreateQrCodeResult = CreateQrCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendWeixinMsessageSoapChannel : Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendWeixinMsessageSoapClient : System.ServiceModel.ClientBase<Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap>, Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap {
        
        public SendWeixinMsessageSoapClient() {
        }
        
        public SendWeixinMsessageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendWeixinMsessageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendWeixinMsessageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendWeixinMsessageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(string openId, string content, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.content = content;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse retVal = ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse> Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageResponse> SendMessageAsync(string openId, string content, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.content = content;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            return ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendImage(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest request) {
            return base.Channel.SendImage(request);
        }
        
        public string SendImage(string openId, string filePath, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.filePath = filePath;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse retVal = ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendImage(inValue);
            return retVal.Body.SendImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse> Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendImageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest request) {
            return base.Channel.SendImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendImageResponse> SendImageAsync(string openId, string filePath, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendImageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.filePath = filePath;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            return ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendTemplateMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest request) {
            return base.Channel.SendTemplateMessage(request);
        }
        
        public string SendTemplateMessage(string openId, string template, string first, string param1, string param2, string param3, string param4, string param5, string remark, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.template = template;
            inValue.Body.first = first;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            inValue.Body.param4 = param4;
            inValue.Body.param5 = param5;
            inValue.Body.remark = remark;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse retVal = ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendTemplateMessage(inValue);
            return retVal.Body.SendTemplateMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse> Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendTemplateMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest request) {
            return base.Channel.SendTemplateMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageResponse> SendTemplateMessageAsync(string openId, string template, string first, string param1, string param2, string param3, string param4, string param5, string remark, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendTemplateMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.template = template;
            inValue.Body.first = first;
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            inValue.Body.param4 = param4;
            inValue.Body.param5 = param5;
            inValue.Body.remark = remark;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            return ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendTemplateMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendChatMessage(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest request) {
            return base.Channel.SendChatMessage(request);
        }
        
        public string SendChatMessage(string openId, string template, string nick, string content, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.template = template;
            inValue.Body.nick = nick;
            inValue.Body.content = content;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse retVal = ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendChatMessage(inValue);
            return retVal.Body.SendChatMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse> Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.SendChatMessageAsync(Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest request) {
            return base.Channel.SendChatMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageResponse> SendChatMessageAsync(string openId, string template, string nick, string content, string timeStamp, string signed) {
            Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.SendChatMessageRequestBody();
            inValue.Body.openId = openId;
            inValue.Body.template = template;
            inValue.Body.nick = nick;
            inValue.Body.content = content;
            inValue.Body.timeStamp = timeStamp;
            inValue.Body.signed = signed;
            return ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).SendChatMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.CreateQrCode(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest request) {
            return base.Channel.CreateQrCode(request);
        }
        
        public string CreateQrCode(string sceneId, string expireSeconds) {
            Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequestBody();
            inValue.Body.sceneId = sceneId;
            inValue.Body.expireSeconds = expireSeconds;
            Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse retVal = ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).CreateQrCode(inValue);
            return retVal.Body.CreateQrCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse> Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap.CreateQrCodeAsync(Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest request) {
            return base.Channel.CreateQrCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeResponse> CreateQrCodeAsync(string sceneId, string expireSeconds) {
            Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest inValue = new Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequest();
            inValue.Body = new Lvy.Trip.AdminSite.SendWeixinMessage.CreateQrCodeRequestBody();
            inValue.Body.sceneId = sceneId;
            inValue.Body.expireSeconds = expireSeconds;
            return ((Lvy.Trip.AdminSite.SendWeixinMessage.SendWeixinMsessageSoap)(this)).CreateQrCodeAsync(inValue);
        }
    }
}
