//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvy.Web.Common.FileUpload {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileUpload.IUploadService")]
    public interface IUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lvy.Web.Common.FileUpload.UploadFileResponse UploadFile(Lvy.Web.Common.FileUpload.UploadFileRequest inputModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> UploadFileAsync(Lvy.Web.Common.FileUpload.UploadFileRequest inputModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lvy.Web.Common.FileUpload.UploadFileResponse UploadPicture(Lvy.Web.Common.FileUpload.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/UploadPicture", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> UploadPictureAsync(Lvy.Web.Common.FileUpload.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/CreateFolder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Lvy.Web.Common.FileUpload.UploadFileResponse CreateFolder(Lvy.Web.Common.FileUpload.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/CreateFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> CreateFolderAsync(Lvy.Web.Common.FileUpload.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileSize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetFileSize(string sourceFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/GetFileSize", ReplyAction="*")]
        System.Threading.Tasks.Task<long> GetFileSizeAsync(string sourceFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DelelteFileByFileName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DelelteFileByFileName(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadService/DelelteFileByFileName", ReplyAction="*")]
        System.Threading.Tasks.Task DelelteFileByFileNameAsync(string fileName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileStreamField;
        
        private string virtualPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FileStream {
            get {
                return this.fileStreamField;
            }
            set {
                this.fileStreamField = value;
                this.RaisePropertyChanged("FileStream");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VirtualPath {
            get {
                return this.virtualPathField;
            }
            set {
                this.virtualPathField = value;
                this.RaisePropertyChanged("VirtualPath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string filePathField;
        
        private int retCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
                this.RaisePropertyChanged("FilePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RetCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("RetCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadServiceChannel : Lvy.Web.Common.FileUpload.IUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadServiceClient : System.ServiceModel.ClientBase<Lvy.Web.Common.FileUpload.IUploadService>, Lvy.Web.Common.FileUpload.IUploadService {
        
        public UploadServiceClient() {
        }
        
        public UploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Lvy.Web.Common.FileUpload.UploadFileResponse UploadFile(Lvy.Web.Common.FileUpload.UploadFileRequest inputModel) {
            return base.Channel.UploadFile(inputModel);
        }
        
        public System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> UploadFileAsync(Lvy.Web.Common.FileUpload.UploadFileRequest inputModel) {
            return base.Channel.UploadFileAsync(inputModel);
        }
        
        public Lvy.Web.Common.FileUpload.UploadFileResponse UploadPicture(Lvy.Web.Common.FileUpload.UploadFileRequest request) {
            return base.Channel.UploadPicture(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> UploadPictureAsync(Lvy.Web.Common.FileUpload.UploadFileRequest request) {
            return base.Channel.UploadPictureAsync(request);
        }
        
        public Lvy.Web.Common.FileUpload.UploadFileResponse CreateFolder(Lvy.Web.Common.FileUpload.UploadFileRequest request) {
            return base.Channel.CreateFolder(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Web.Common.FileUpload.UploadFileResponse> CreateFolderAsync(Lvy.Web.Common.FileUpload.UploadFileRequest request) {
            return base.Channel.CreateFolderAsync(request);
        }
        
        public long GetFileSize(string sourceFile) {
            return base.Channel.GetFileSize(sourceFile);
        }
        
        public System.Threading.Tasks.Task<long> GetFileSizeAsync(string sourceFile) {
            return base.Channel.GetFileSizeAsync(sourceFile);
        }
        
        public void DelelteFileByFileName(string fileName) {
            base.Channel.DelelteFileByFileName(fileName);
        }
        
        public System.Threading.Tasks.Task DelelteFileByFileNameAsync(string fileName) {
            return base.Channel.DelelteFileByFileNameAsync(fileName);
        }
    }
}
