<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PetaPoco.Compiled" Version="6.0.532" />
    <PackageReference Include="System.Text.Json" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arch.Common\Lvy.Common.csproj" />
  </ItemGroup>

</Project>
