//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvy.Trip.Weixin.LinkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LinkService.LinkServiceSoap")]
    public interface LinkServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sceneId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeixinQrRtn", ReplyAction="*")]
        Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse WeixinQrRtn(Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WeixinQrRtn", ReplyAction="*")]
        System.Threading.Tasks.Task<Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse> WeixinQrRtnAsync(Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeixinQrRtnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeixinQrRtn", Namespace="http://tempuri.org/", Order=0)]
        public Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequestBody Body;
        
        public WeixinQrRtnRequest() {
        }
        
        public WeixinQrRtnRequest(Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeixinQrRtnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sceneId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountCode;
        
        public WeixinQrRtnRequestBody() {
        }
        
        public WeixinQrRtnRequestBody(string sceneId, string accountCode) {
            this.sceneId = sceneId;
            this.accountCode = accountCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeixinQrRtnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeixinQrRtnResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponseBody Body;
        
        public WeixinQrRtnResponse() {
        }
        
        public WeixinQrRtnResponse(Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeixinQrRtnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WeixinQrRtnResult;
        
        public WeixinQrRtnResponseBody() {
        }
        
        public WeixinQrRtnResponseBody(string WeixinQrRtnResult) {
            this.WeixinQrRtnResult = WeixinQrRtnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LinkServiceSoapChannel : Lvy.Trip.Weixin.LinkService.LinkServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkServiceSoapClient : System.ServiceModel.ClientBase<Lvy.Trip.Weixin.LinkService.LinkServiceSoap>, Lvy.Trip.Weixin.LinkService.LinkServiceSoap {
        
        public LinkServiceSoapClient() {
        }
        
        public LinkServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse Lvy.Trip.Weixin.LinkService.LinkServiceSoap.WeixinQrRtn(Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest request) {
            return base.Channel.WeixinQrRtn(request);
        }
        
        public string WeixinQrRtn(string sceneId, string accountCode) {
            Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest inValue = new Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest();
            inValue.Body = new Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequestBody();
            inValue.Body.sceneId = sceneId;
            inValue.Body.accountCode = accountCode;
            Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse retVal = ((Lvy.Trip.Weixin.LinkService.LinkServiceSoap)(this)).WeixinQrRtn(inValue);
            return retVal.Body.WeixinQrRtnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse> Lvy.Trip.Weixin.LinkService.LinkServiceSoap.WeixinQrRtnAsync(Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest request) {
            return base.Channel.WeixinQrRtnAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lvy.Trip.Weixin.LinkService.WeixinQrRtnResponse> WeixinQrRtnAsync(string sceneId, string accountCode) {
            Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest inValue = new Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequest();
            inValue.Body = new Lvy.Trip.Weixin.LinkService.WeixinQrRtnRequestBody();
            inValue.Body.sceneId = sceneId;
            inValue.Body.accountCode = accountCode;
            return ((Lvy.Trip.Weixin.LinkService.LinkServiceSoap)(this)).WeixinQrRtnAsync(inValue);
        }
    }
}
